### PR TITLE
added CSS to Navigation to match Site theme

### PR DESCRIPTION
**Pull request by amnjain**
Hi @CookieJari 
Please approve and merge the PR.

Thanks!

### CODE REVIEW

**Comment by CookieJari** [comment]
One of the requirements is that the button in the header section stays the same color.

**Comment by amnjain** [comment]
Oh Okay! Let me revert that Button Changes alone!

Are you talking about that Sign Up Button?

**Comment by CookieJari** [comment]
Yep the sign up button

**Comment by amnjain** [comment]
Hi @CookieJari 
I have reverted those changes. Please approve and merge it!

**Comment by CookieJari** [comment]
Thanks!

**Pull request merged**
